import type { Metadata } from "next";
import { Mukta } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components";
import { Strip } from "@/components/Strip";

const roboto = Mukta({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>

      <body className={`w-screen min-h-screen ${roboto.className}`}>
        <Strip />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
